--- 
- hosts: all
  become: yes
  pre_tasks:

  - name: Update reposiroty index (Centos)
    tags: always
    dnf:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "CentOS"

  - name: update repository index (Ubuntu)
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"

- hosts: all
  become: true
  roles: 
    - base

- hosts: all
  become: true
  roles:
    - web_servers

- hosts: all
  become: true
  roles:
    - db_servers

- hosts: file_servers
  become: true
  roles:
    - file_servers


#  - name: change e-mail address from admin
#    tags: apache, centos, httpd
#    lineinfile:
#      path: /etc/httpd/conf/httpd.conf
#      regexp: '^ServerAdmin'
#      line: ServerAdmin darek@darek.net
#    when: ansible_distribution == "CentOS"
#    register: httpd


 # - name: Ensure system is upgraded 
 #   dnf:
 #     name: "*"
 #     state: latest
