---
- hosts: all
  become: yes
  tasks:
  - name: Update reposiroty index
    dnf:
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: ensure httpd is installed
    dnf:
      name:
        - httpd
        - php
      state: present
    when: ansible_distribution == "CentOS"

 # - name: Ensure system is upgraded 
 #   dnf:
 #     name: "*"
 #     state: latest
