- name: ensure mariadb is installed (Centos)
  dnf:
    name: mariadb
    state: latest
  when: ansible_distribution == "CentOS"

- name: ensure mariadb is installed (Ubuntu)
  apt:
    name: mariadb-server
    state: latest
  when: ansible_distribution == "Ubuntu"

